MAIOR_INTEIRO = 255
MAIOR_REGISTRADOR = ord('D')
MENOR_REGISTRADOR = ord('A')
TAMANHO_MEMORIA_REAL = 32
TAMANHO_MEMORIA_COD = TAMANHO_MEMORIA_REAL / 2
TAMANHO_MEMORIA_DADOS = TAMANHO_MEMORIA_REAL / 2
